name: exotic
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - arrow-cpp=0.11.1
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.68.0
  - bzip2=1.0.6
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2019.11.28
  - cffi=1.12.3
  - cryptography=2.7
  - dbus=1.13.6
  - decorator=4.3.2
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - graphite2=1.3.13
  - graphviz=2.38.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.9.0
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.1
  - ipykernel=5.1.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - json5=0.9.1
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.36
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libtool=2.4.6
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1d
  - pandas=0.24.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parquet-cpp=1.5.1
  - parso=0.3.4
  - pcre=8.43
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - pixman=0.34.0
  - prometheus_client=0.6.0
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=19.0.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - python=3.7.2
  - python-dateutil=2.8.0
  - python-graphviz=0.10.1
  - pytz=2018.9
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - retrying=1.3.3
  - scikit-learn=0.20.3
  - send2trash=1.5.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - terminado=0.8.1
  - testpath=0.4.2
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.5.1
  - xarray=0.14.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.2
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.3
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - atomicwrites==1.3.0
    - cftime==1.0.3.4
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==0.8.0
    - coverage==4.5.3
    - cycler==0.10.0
    - dask==2.5.0
    - distributed==2.5.1
    - heapdict==1.0.0
    - kiwisolver==1.0.1
    - lmoments==0.2.2
    - lmoments3==1.0.4
    - locket==0.2.0
    - matplotlib==3.0.3
    - more-itertools==6.0.0
    - msgpack==0.6.1
    - netcdf4==1.4.3.2
    - numdifftools==0.9.39
    - partd==0.3.9
    - pluggy==0.9.0
    - prompt-toolkit==1.0.14
    - psutil==5.6.1
    - py==1.8.0
    - pyarrow==0.12.1
    - pyinquirer==1.0.3
    - pyparsing==2.3.1
    - pytest==4.3.0
    - pytest-cov==2.6.1
    - pyyaml==5.1.2
    - regex==2019.8.19
    - requests==2.21.0
    - scipy==1.2.1
    - slack-progress==0.5
    - slackclient==1.3.1
    - slacker==0.13.0
    - sortedcontainers==2.1.0
    - tblib==1.3.2
    - toolz==0.9.0
    - urllib3==1.24.2
    - websocket-client==0.54.0
    - zict==0.1.4

